name: depfold
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python=3.8
  - pip=21.0.1
  - numpy>=1.21.0
  - pytorch>=1.10.0
  - cudatoolkit>=11.3
  - viennarna>=2.5.0
  - pip:
    - transformers>=4.12.0
    - tqdm>=4.62.3
    - scikit-learn>=1.0.1
    - pandas>=1.3.4
    - matplotlib>=3.5.0
    - seaborn>=0.11.2